lb:
  build: lb/
  command: python app.py
  ports:
   - "5000:5000"
  volumes:
   - ./lb/:/code
web:
  build: app/
  command: python app.py
  volumes:
   - ./app/:/code
  links:
   - redis
   - lb
redis:
  image: redis
